apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: kube-cert-manager
  name: kube-cert-manager
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kube-cert-manager
      name: kube-cert-manager
    spec:
      containers:
        - name: kube-cert-manager
          image: gcr.io/livegrep/kube-cert-manager@sha256:880ea5905b709d81a3f2e637e40de264562698ffc408ee5a1a474fe775d3ff93
          args:
            - "-data-dir=/var/lib/cert-manager"
            - "-acme-url=https://acme-v01.api.letsencrypt.org/directory"
            - "-renew-before-days=30"
          volumeMounts:
            - name: data
              mountPath: /var/lib/cert-manager
            - mountPath: /var/run/secrets/gcp
              name: gcp
              readOnly: true
          env:
            - name: GCE_PROJECT
              value: livegrep
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/run/secrets/gcp/service-account.json
      volumes:
        - name: "data"
          gcePersistentDisk:
            pdName: kube-cert-manager
            fsType: ext4
        - name: gcp
          secret:
            defaultMode: 0644
            secretName: gcp.cert-manager
