kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
  namespace: default
data:
  www.conf: |
      server {
        listen 80;
        server_name www.livegrep.com;
        return 301 https://livegrep.com$request_uri;
      }
